name: Metrics
on:
  # æ¯å¤©åŠå¤œ 0 ç‚¹è‡ªåŠ¨æ›´æ–°
  schedule: [{cron: "0 0 * * *"}]
  # å…è®¸æ‰‹åŠ¨è§¦å‘
  workflow_dispatch:
  # æ¨é€ä»£ç æ—¶è§¦å‘
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: sLingli
          template: classic
          base: "" 
          config_timezone: Asia/Shanghai
          
          # ğŸ± å¼€å¯çŒ«å’ªæ’ä»¶
          plugin_tamagotchi: yes
          plugin_tamagotchi_symbol: ğŸ±
          plugin_tamagotchi_gif: yes
          plugin_tamagotchi_carrier: yes
